spring.application.name=Trackyfly
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://72.61.254.236:3312/trackyfly?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=yellapusatyasai@gmail.com
spring.datasource.password=@SaiDivya2503
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
trackyfly.jwt.secret=satyainfotechnetworkstrackyflysupersecretkeyforjwtgeneration1234567890
trackyfly.jwt.expirationMs=86400000
